create or replace view v_declaracion_jurada  as
select distinct(p.id),
       p.version,
       p.codigo,
       p.nombre,
       apellidos,
       nombres,
       fecha_nacimiento,
       calcular_edad(p.fecha_nacimiento) edad,
       lugar_nacimiento,
       p.sexo,
       estado_civil,
       paraguayo,
       indigena,
       etnia,
       (select nombre from etnia_indigena where id=p.etnia) nombre_etnia,
       comunidad,
       icv,
       tipo_pobreza,
       cedula,
       fecha_expedicion_cedula,
       fecha_vencimiento_cedula,
       carnet_militar,
       pariente,
       parentesco,
       hogar_colectivo,
       fecha_ingreso_hogar,
       departamento,
      (select nombre from departamento d where d.id=p.departamento) nom_departamento,
       distrito,
      (select codigo from distrito di where di.id=p.distrito )cod_distrito,
      (select nombre from distrito di where di.id=p.distrito )nom_distrito,
      (select r.numero from region r, departamento d where r.numero=d.region
      and p.departamento=d.id) codigo_region,
      (select r.codigo from region r, departamento d  where r.numero=d.region
      and p.departamento=d.id) nom_region,
       tipo_area,
      (select t.numero from tipo_area t where t.numero=p.tipo_area)tip_area,
       barrio,
      (select b.codigo from barrio b  where b.id=p.barrio) cod_barrio,
      (select b.nombre from barrio b  where b.id=p.barrio) nom_barrio,
       direccion,
       telefono_linea_baja,
       telefono_celular,
       cedula_representante,
       nombre_representante,
       fecha_otorgamiento,
       cedula_curador,
       nombre_curador,
       nombre_juzgado,
       fecha_sentencia,
       numero_sentencia,
       sello_registro,
       numero_sime_tutelaje,
       observaciones_anular_tutelaje,
       certificado_matrimonio,
       oficina_matrimonio,
       fecha_acta_matrimonio,
       tomo_matrimonio,
       folio_matrimonio,
       acta_matrimonio,
       cedula_conyuge,
       nombre_conyuge,
       fecha_matrimonio,
       fecha_certificado_matrimonio,
       numero_sime_matrimonio,
       observac_anular_matrimon_43115,
       certificado_defuncion,
       oficina_defuncion,
       fecha_acta_defuncion,
       tomo_defuncion,
       folio_defuncion,
       acta_defuncion,
       fecha_defuncion,
       fecha_certificado_defuncion,
       numero_sime_defuncion,
       observaciones_anular_defuncion,
       certificado_invalidez,
       diagnostico_invalidez,
       fecha_certificado_invalidez,
       numero_sime_invalidez,
       observaciones_anular_invalidez,
       banco,
       p.cuenta_bancaria,
       numero_sime_cuenta,
       observaciones_anular_cuenta,
       ficha,
       numero_sime_ficha,
       observaciones_anular_ficha,
       monitoreado,
       fecha_monitoreo,
       monitoreo_sorteo,
       salario,
       porcentaje,
   --    unidad_salario,
   --    fecha_salario,
       numero_sime_salario,
       observaciones_anular_salario,
       fecha_ingreso,
       fecha_egreso,
       tipo,
       cantidad,
       modelo,
       ano_registro,
       numero_sime_automotor,
       observaciones_anular_automotor,
       fecha_nacimientos,
       departamento_nacimiento,
       distrito_nacimiento,
       nombre_madre,
       cedula_madre,
       nombre_padre,
       cedula_padre,
       folio_nacimiento,
       acta_nacimiento,
       tomo_nacimiento,
       numero_sime_nacimiento,
       observac_anular_nacimien_13191,
       ruc_entidad,
       denominacion_entidad,
       numero_sime_proveedor,
       observaciones_anular_proveedor,
       fecha_ingreso_catastro,
       fecha_egreso_catastro,
       tipo_catastro,
       cantidad_inmueble,
       monto_catastro,
       numero_sime_catastro,
       observaciones_anular_catastro,
       fecha_ingreso_cotizante,
       fecha_egreso_cotizante,
       monto_cotizante,
       nombres_empresa,
       ruc,
       numero_sime_cotizante,
       observaciones_anular_cotizante,
       fecha_ingreso_senacsa,
       fecha_egreso_senacsa,
       tipo_senacsa,
       cantidad_senacsa,
       monto_senacsa,
       numero_sime_senacsa,
       observaciones_anular_senacsa,
       edicion_restringida
  from persona p;
/