/*
 * Este programa es software libre; usted puede redistribuirlo y/o modificarlo bajo los terminos
 * de la licencia "GNU General Public License" publicada por la Fundacion "Free Software Foundation".
 * Este programa se distribuye con la esperanza de que pueda ser util, pero SIN NINGUNA GARANTIA;
 * vea la licencia "GNU General Public License" para obtener mas informacion.
 */
/*
 * author: ADALID
 * template: templates/jee1/oracle/views/create-data-provider-view.sql.vm
 * template-author: Jorge Campins
 */
exec xsp.dropone('view', 'consulta_persona');
create view consulta_persona as
select
    persona.id,
    persona.version,
    persona.codigo,
    persona.nombre,
    persona.cedula,
    persona.cedula_no_identificacion,
    persona.apellidos,
    persona.nombres,
    persona.fecha_nacimiento,
    persona.lugar_nacimiento,
    persona.referencia,
    persona.nombre_referente,
    persona.telefono_referente,
    persona.apodo,
    persona.sexo,
    persona.estado_civil,
    persona.paraguayo,
    persona.fecha_expedicion_cedula,
    persona.fecha_vencimiento_cedula,
    persona.indigena,
    persona.etnia,
    persona.comunidad,
    persona.icv,
    persona.tipo_pobreza,
    persona.carnet_militar,
    persona.jerarquia,
    persona.pais,
    persona.extranjero,
    persona.pariente,
    persona.parentesco,
    persona.hogar_colectivo,
    persona.fecha_ingreso_hogar,
    persona.departamento,
    persona.distrito,
    persona.tipo_area,
    persona.barrio,
    persona.manzana,
    persona.direccion,
    persona.coordenada_x,
    persona.coordenada_y,
    persona.url_google_maps,
    persona.telefono_linea_baja,
    persona.telefono_celular,
    persona.cedula_representante_identif,
    persona.cedula_representante,
    persona.nombre_representante,
    persona.fecha_otorgamiento,
    persona.cedula_curador_identif,
    persona.cedula_curador,
    persona.nombre_curador,
    persona.nombre_juzgado,
    persona.fecha_sentencia,
    persona.numero_sentencia,
    persona.sello_registro,
    persona.numero_sime_tutelaje,
    persona.observaciones_anular_tutelaje,
    persona.certificado_matrimonio,
    persona.oficina_matrimonio,
    persona.fecha_acta_matrimonio,
    persona.tomo_matrimonio,
    persona.folio_matrimonio,
    persona.acta_matrimonio,
    persona.cedula_conyuge,
    persona.nombre_conyuge,
    persona.fecha_matrimonio,
    persona.fecha_certificado_matrimonio,
    persona.numero_sime_matrimonio,
    persona.observac_anular_matrimon_43115,
    persona.certificado_defuncion,
    persona.oficina_defuncion,
    persona.fecha_acta_defuncion,
    persona.tomo_defuncion,
    persona.folio_defuncion,
    persona.acta_defuncion,
    persona.fecha_defuncion,
    persona.fecha_certificado_defuncion,
    persona.numero_sime_defuncion,
    persona.departamentodef,
    persona.distritodef,
    persona.nombre_registro,
    persona.lugar_fallecido,
    persona.nacionalidad,
    persona.edad,
    persona.lugar_nacimiento_def,
    persona.fecha_nacimiento_defu,
    persona.observaciones_anular_defuncion,
    persona.certificado_invalidez,
    persona.diagnostico_invalidez,
    persona.fecha_certificado_invalidez,
    persona.numero_sime_invalidez,
    persona.observaciones_anular_invalidez,
    persona.banco,
    persona.cuenta_bancaria,
    persona.tarjeta_debito,
    persona.estado_bancaria,
    persona.fecha_bancaria,
    persona.cuentabloqueada,
    persona.numero_sime_cuenta,
    persona.observaciones_anular_cuenta,
    persona.ficha,
    persona.numero_sime_ficha,
    persona.observaciones_anular_ficha,
    persona.monitoreado,
    persona.fecha_monitoreo,
    persona.monitoreo_sorteo,
    persona.observaciones_ficha,
    persona.salario,
    persona.porcentaje,
    persona.numero_sime_salario,
    persona.observaciones_anular_salario,
    persona.fecha_ingreso_emp,
    persona.fecha_egreso_emp,
    persona.monto_emp,
    persona.nombre_empresa_emp,
    persona.numero_sime_emp,
    persona.observaciones_anular_emp,
    persona.fecha_ingreso_ext,
    persona.fecha_egreso_ext,
    persona.monto_ext,
    persona.nombre_empresa_ext,
    persona.numero_sime_ext,
    persona.observaciones_anular_ext,
    persona.fecha_ingreso_jubi,
    persona.fecha_egreso_jubi,
    persona.monto_jubi,
    persona.nombre_empresa,
    persona.numero_sime_jubi,
    persona.observaciones_anular_jubi,
    persona.fecha_ingreso_sub,
    persona.fecha_egreso_sub,
    persona.monto_sub,
    persona.nombre_empresa_sub,
    persona.numero_sime_sub,
    persona.observaciones_anular_sub,
    persona.fecha_ingreso,
    persona.fecha_egreso,
    persona.tipo,
    persona.cantidad,
    persona.modelo,
    persona.ano_registro,
    persona.monto,
    persona.numero_sime_automotor,
    persona.observaciones_anular_automotor,
    persona.fecha_nacimientos,
    persona.departamento_nacimiento,
    persona.distrito_nacimiento,
    persona.cedula_madre,
    persona.nombre_madre,
    persona.cedula_padre,
    persona.nombre_padre,
    persona.folio_nacimiento,
    persona.acta_nacimiento,
    persona.tomo_nacimiento,
    persona.numero_sime_nacimiento,
    persona.observac_anular_nacimien_13191,
    persona.tipo_proveedor,
    persona.ruc_entidad,
    persona.denominacion_entidad,
    persona.numero_sime_proveedor,
    persona.observaciones_anular_proveedor,
    persona.fecha_ingreso_catastro,
    persona.fecha_egreso_catastro,
    persona.tipo_catastro,
    persona.cantidad_inmueble,
    persona.monto_catastro,
    persona.numero_sime_catastro,
    persona.observaciones_anular_catastro,
    persona.fecha_ingreso_cotizante,
    persona.fecha_egreso_cotizante,
    persona.monto_cotizante,
    persona.nombres_empresa,
    persona.ruc,
    persona.numero_sime_cotizante,
    persona.observaciones_anular_cotizante,
    persona.estancia,
    persona.fecha_ingreso_senacsa,
    persona.fecha_egreso_senacsa,
    persona.tipo_senacsa,
    persona.cantidad_senacsa,
    persona.monto_senacsa,
    persona.numero_sime_senacsa,
    persona.observaciones_anular_senacsa,
    persona.nombre_entidad,
    persona.numero_sime,
    persona.observaciones_anular_no_indig,
    persona.numero_cedula_resid,
    persona.nombres_resid,
    persona.apellidos_resid,
    persona.ano_votacion,
    persona.pais_resid,
    persona.domicilio,
    persona.fecha_inscripcion,
    persona.numero_sime_residente,
    persona.observaciones_anular_resid,
    persona.nro_sentencia_heredero,
    persona.fecha_sentencia_heredero,
    persona.juzgado,
    persona.ciudad,
    persona.sello,
    persona.numero_sime_sentencia,
    persona.observaciones_anular_sentencia,
    persona.objecion_menor,
    persona.edicion_restringida,
        cedula_1.numero as numero_1,
        cedula_1.nombre as nombre_1,
        sexo_persona_2.numero as numero_2,
        sexo_persona_2.codigo as codigo_2,
        estado_civil_3.numero as numero_3,
        estado_civil_3.codigo as codigo_3,
        etnia_indigena_4.codigo as codigo_4,
        etnia_indigena_4.nombre as nombre_4,
        comunidad_indigena_5.codigo as codigo_5,
        comunidad_indigena_5.nombre as nombre_5,
        tipo_pobreza_6.numero as numero_6,
        tipo_pobreza_6.codigo as codigo_6,
        pais_7.codigo as codigo_7,
        pais_7.nombre as nombre_7,
        persona_8.codigo as codigo_8,
        persona_8.nombre as nombre_8,
        parentesco_9.numero as numero_9,
        parentesco_9.codigo as codigo_9,
        hogar_colectivo_10.codigo as codigo_10,
        hogar_colectivo_10.nombre as nombre_10,
        departamento_11.codigo as codigo_11,
        departamento_11.nombre as nombre_11,
        distrito_12.codigo as codigo_12,
        distrito_12.nombre as nombre_12,
        tipo_area_13.numero as numero_13,
        tipo_area_13.codigo as codigo_13,
        barrio_14.codigo as codigo_14,
        barrio_14.nombre as nombre_14,
        persona_15.codigo as codigo_15,
        persona_15.nombre as nombre_15,
        persona_16.codigo as codigo_16,
        persona_16.nombre as nombre_16,
        oficina_registral_18.codigo as codigo_18,
        oficina_registral_18.nombre as nombre_18,
        oficina_registral_20.codigo as codigo_20,
        oficina_registral_20.nombre as nombre_20,
        departamento_22.codigo as codigo_22,
        departamento_22.nombre as nombre_22,
        distrito_23.codigo as codigo_23,
        distrito_23.nombre as nombre_23,
        banco_25.codigo as codigo_25,
        banco_25.nombre as nombre_25,
        ficha_persona_27.codigo as codigo_27,
        ficha_persona_27.nombre as nombre_27,
        departamento_35.codigo as codigo_35,
        departamento_35.nombre as nombre_35,
        distrito_36.codigo as codigo_36,
        distrito_36.nombre as nombre_36,
        tipo_persona_38.numero as numero_38,
        tipo_persona_38.codigo as codigo_38,
        pais_44.codigo as codigo_44,
        pais_44.nombre as nombre_44
    from persona
    left outer join cedula cedula_1 on cedula_1.id = persona.cedula
    left outer join sexo_persona sexo_persona_2 on sexo_persona_2.numero = persona.sexo
    left outer join estado_civil estado_civil_3 on estado_civil_3.numero = persona.estado_civil
    left outer join etnia_indigena etnia_indigena_4 on etnia_indigena_4.id = persona.etnia
    left outer join comunidad_indigena comunidad_indigena_5 on comunidad_indigena_5.id = persona.comunidad
    left outer join tipo_pobreza tipo_pobreza_6 on tipo_pobreza_6.numero = persona.tipo_pobreza
    left outer join pais pais_7 on pais_7.id = persona.pais
    left outer join persona persona_8 on persona_8.id = persona.pariente
    left outer join parentesco parentesco_9 on parentesco_9.numero = persona.parentesco
    left outer join hogar_colectivo hogar_colectivo_10 on hogar_colectivo_10.id = persona.hogar_colectivo
    inner join departamento departamento_11 on departamento_11.id = persona.departamento
    inner join distrito distrito_12 on distrito_12.id = persona.distrito
    left outer join tipo_area tipo_area_13 on tipo_area_13.numero = persona.tipo_area
    left outer join barrio barrio_14 on barrio_14.id = persona.barrio
    left outer join persona persona_15 on persona_15.id = persona.cedula_representante_identif
    left outer join persona persona_16 on persona_16.id = persona.cedula_curador_identif
    left outer join oficina_registral oficina_registral_18 on oficina_registral_18.id = persona.oficina_matrimonio
    left outer join oficina_registral oficina_registral_20 on oficina_registral_20.id = persona.oficina_defuncion
    left outer join departamento departamento_22 on departamento_22.id = persona.departamentodef
    left outer join distrito distrito_23 on distrito_23.id = persona.distritodef
    left outer join banco banco_25 on banco_25.id = persona.banco
    left outer join ficha_persona ficha_persona_27 on ficha_persona_27.id = persona.ficha
    left outer join departamento departamento_35 on departamento_35.id = persona.departamento_nacimiento
    left outer join distrito distrito_36 on distrito_36.id = persona.distrito_nacimiento
    left outer join tipo_persona tipo_persona_38 on tipo_persona_38.numero = persona.tipo_proveedor
    left outer join pais pais_44 on pais_44.id = persona.pais_resid
;
