create or replace function pension$genera_estad$82701$biz(x$super number, x$observaciones nvarchar2) return number is
    v$err constant number := -20000; -- an integer in the range -20000..-20999
    v$msg nvarchar2(2000); -- a character string of at most 2048 bytes?
begin
  Insert into dim_usuario
    Select id_usuario,nombre_usuario from usuario
  Where id_usuario not in ( select id_usuario from dim_usuario);

  Insert into tmp_pension (id, VERSION, CODIGO, CLASE, PERSONA, CAUSANTE, SALDO_INICIAL, SALDO_ACTUAL, MONTO_PAGADO, NUMERO_SIME, NUMERO_SIME_ENTRADA, ARCHIVO,
                          LINEA, ESTADO, FECHA_TRANSICION, USUARIO_TRANSICION, OBSERVACIONES, ACTIVA, FECHA_ACTIVAR, USUARIO_ACTIVAR, OBSERVACIONES_ACTIVAR,
                          FECHA_INACTIVAR, USUARIO_INACTIVAR, OBSERVACIONES_INACTIVAR, IRREGULAR, FECHA_IRREGULAR, TIENE_OBJECION, FALTA_REQUISITO, TIENE_DENUNCIA,
                          TIENE_RECLAMO, DICTAMEN_DENEGAR, FECHA_DICTAMEN_DENEGAR, RESUMEN_DICTAMEN_DENEGAR, CAUSA_DENEGAR, OTRAS_CAUSAS_DENEGAR, RESOLUCION_DENEGAR,
                          FECHA_RESOLUCION_DENEGAR, RESUMEN_RESOLUCION_DENEGAR, RECLAMO_OTORGAR, DICTAMEN_OTORGAR, FECHA_DICTAMEN_OTORGAR, RESUMEN_DICTAMEN_OTORGAR,
                          RESOLUCION_OTORGAR, FECHA_RESOLUCION_OTORGAR, RESUMEN_RESOLUCION_OTORGAR, DICTAMEN_REVOCAR, FECHA_DICTAMEN_REVOCAR, RESUMEN_DICTAMEN_REVOCAR,
                          CAUSA_REVOCAR, OTRAS_CAUSAS_REVOCAR, RESOLUCION_REVOCAR, FECHA_RESOLUCION_REVOCAR, RESUMEN_RESOLUCION_REVOCAR, RECLAMO_REACTIVAR, CAUSA_FINALIZAR,
                          OTRAS_CAUSAS_FINALIZAR, MONTO_EXCESO, MONTO_REINTEGRO, MONTO_DEUDA, EXPEDIENTE_ACUERDO, DESCRIPCION_ACUERDO, FECHA_ACUERDO, PERSONA_DEUDOR, MONTO_CUOTA,
                          SALDO_DEUDOR )
    Select ID, VERSION, CODIGO, CLASE, PERSONA, CAUSANTE, SALDO_INICIAL, SALDO_ACTUAL, MONTO_PAGADO, NUMERO_SIME, NUMERO_SIME_ENTRADA, ARCHIVO,
            LINEA, ESTADO, FECHA_TRANSICION, USUARIO_TRANSICION, OBSERVACIONES, ACTIVA, FECHA_ACTIVAR, USUARIO_ACTIVAR, OBSERVACIONES_ACTIVAR,
            FECHA_INACTIVAR, USUARIO_INACTIVAR, OBSERVACIONES_INACTIVAR, IRREGULAR, FECHA_IRREGULAR, TIENE_OBJECION, FALTA_REQUISITO, TIENE_DENUNCIA,
            TIENE_RECLAMO, DICTAMEN_DENEGAR, FECHA_DICTAMEN_DENEGAR, RESUMEN_DICTAMEN_DENEGAR, CAUSA_DENEGAR, OTRAS_CAUSAS_DENEGAR, RESOLUCION_DENEGAR,
            FECHA_RESOLUCION_DENEGAR, RESUMEN_RESOLUCION_DENEGAR, RECLAMO_OTORGAR, DICTAMEN_OTORGAR, FECHA_DICTAMEN_OTORGAR, RESUMEN_DICTAMEN_OTORGAR,
            RESOLUCION_OTORGAR, FECHA_RESOLUCION_OTORGAR, RESUMEN_RESOLUCION_OTORGAR, DICTAMEN_REVOCAR, FECHA_DICTAMEN_REVOCAR, RESUMEN_DICTAMEN_REVOCAR,
            CAUSA_REVOCAR, OTRAS_CAUSAS_REVOCAR, RESOLUCION_REVOCAR, FECHA_RESOLUCION_REVOCAR, RESUMEN_RESOLUCION_REVOCAR, RECLAMO_REACTIVAR, CAUSA_FINALIZAR,
            OTRAS_CAUSAS_FINALIZAR, MONTO_EXCESO, MONTO_REINTEGRO, MONTO_DEUDA, EXPEDIENTE_ACUERDO, DESCRIPCION_ACUERDO, FECHA_ACUERDO, PERSONA_DEUDOR, MONTO_CUOTA,
            SALDO_DEUDOR
    From pension 
    Where pension.id not in(select id from tmp_pension);

  INSERT INTO tmp_persona(ID, VERSION, CODIGO, NOMBRE, APELLIDOS, NOMBRES, FECHA_NACIMIENTO, LUGAR_NACIMIENTO, SEXO, ESTADO_CIVIL, PARAGUAYO, INDIGENA, ETNIA,
                          COMUNIDAD, ICV, TIPO_POBREZA, CEDULA, FECHA_EXPEDICION_CEDULA, FECHA_VENCIMIENTO_CEDULA, CARNET_MILITAR, PAIS, EXTRANJERO, PARIENTE,
                          PARENTESCO, HOGAR_COLECTIVO, FECHA_INGRESO_HOGAR, DEPARTAMENTO, DISTRITO, TIPO_AREA, BARRIO, DIRECCION, TELEFONO_LINEA_BAJA, TELEFONO_CELULAR,
                          CEDULA_REPRESENTANTE, NOMBRE_REPRESENTANTE, FECHA_OTORGAMIENTO, CEDULA_CURADOR, NOMBRE_CURADOR, NOMBRE_JUZGADO, FECHA_SENTENCIA, NUMERO_SENTENCIA,
                          SELLO_REGISTRO, NUMERO_SIME_TUTELAJE, OBSERVACIONES_ANULAR_TUTELAJE, CERTIFICADO_MATRIMONIO, OFICINA_MATRIMONIO, FECHA_ACTA_MATRIMONIO, TOMO_MATRIMONIO,
                          FOLIO_MATRIMONIO, ACTA_MATRIMONIO, CEDULA_CONYUGE, NOMBRE_CONYUGE, FECHA_MATRIMONIO, FECHA_CERTIFICADO_MATRIMONIO, NUMERO_SIME_MATRIMONIO, OBSERVAC_ANULAR_MATRIMON_43115,
                          CERTIFICADO_DEFUNCION, OFICINA_DEFUNCION, FECHA_ACTA_DEFUNCION, TOMO_DEFUNCION, FOLIO_DEFUNCION, ACTA_DEFUNCION, FECHA_DEFUNCION, FECHA_CERTIFICADO_DEFUNCION,
                          NUMERO_SIME_DEFUNCION, OBSERVACIONES_ANULAR_DEFUNCION, CERTIFICADO_INVALIDEZ, DIAGNOSTICO_INVALIDEZ, FECHA_CERTIFICADO_INVALIDEZ, NUMERO_SIME_INVALIDEZ,
                          OBSERVACIONES_ANULAR_INVALIDEZ, BANCO, CUENTA_BANCARIA, NUMERO_SIME_CUENTA, OBSERVACIONES_ANULAR_CUENTA, FICHA, NUMERO_SIME_FICHA, OBSERVACIONES_ANULAR_FICHA,
                          MONITOREADO, FECHA_MONITOREO, MONITOREO_SORTEO, OBSERVACIONES_FICHA, SALARIO, PORCENTAJE, NUMERO_SIME_SALARIO, OBSERVACIONES_ANULAR_SALARIO, FECHA_INGRESO,
                          FECHA_EGRESO, TIPO, CANTIDAD, MODELO, ANO_REGISTRO, MONTO, NUMERO_SIME_AUTOMOTOR, OBSERVACIONES_ANULAR_AUTOMOTOR, FECHA_NACIMIENTOS, DEPARTAMENTO_NACIMIENTO,
                          DISTRITO_NACIMIENTO, NOMBRE_MADRE, CEDULA_MADRE, NOMBRE_PADRE, CEDULA_PADRE, FOLIO_NACIMIENTO, ACTA_NACIMIENTO, TOMO_NACIMIENTO, NUMERO_SIME_NACIMIENTO,
                          OBSERVAC_ANULAR_NACIMIEN_13191, TIPO_PROVEEDOR, RUC_ENTIDAD, DENOMINACION_ENTIDAD, NUMERO_SIME_PROVEEDOR, OBSERVACIONES_ANULAR_PROVEEDOR, FECHA_INGRESO_CATASTRO,
                          FECHA_EGRESO_CATASTRO, TIPO_CATASTRO, CANTIDAD_INMUEBLE, MONTO_CATASTRO, NUMERO_SIME_CATASTRO, OBSERVACIONES_ANULAR_CATASTRO, FECHA_INGRESO_COTIZANTE, FECHA_EGRESO_COTIZANTE,
                          MONTO_COTIZANTE, NOMBRES_EMPRESA, RUC, NUMERO_SIME_COTIZANTE, OBSERVACIONES_ANULAR_COTIZANTE, FECHA_INGRESO_SENACSA, FECHA_EGRESO_SENACSA, TIPO_SENACSA, CANTIDAD_SENACSA,
                          MONTO_SENACSA, NUMERO_SIME_SENACSA, OBSERVACIONES_ANULAR_SENACSA, EDICION_RESTRINGIDA, NOM_DEPARTAMENTO, NOM_DISTRITO)
    Select a.ID, a.VERSION, a.CODIGO, a.NOMBRE, APELLIDOS, NOMBRES, FECHA_NACIMIENTO, LUGAR_NACIMIENTO, SEXO, a.ESTADO_CIVIL, PARAGUAYO, INDIGENA, ETNIA,
           COMUNIDAD, ICV, a.TIPO_POBREZA, a.CEDULA, FECHA_EXPEDICION_CEDULA, FECHA_VENCIMIENTO_CEDULA, CARNET_MILITAR, a.PAIS, EXTRANJERO, PARIENTE,
           a.PARENTESCO, a.HOGAR_COLECTIVO, FECHA_INGRESO_HOGAR, a.DEPARTAMENTO, a.DISTRITO, a.TIPO_AREA, a.BARRIO, DIRECCION, TELEFONO_LINEA_BAJA, TELEFONO_CELULAR,
           CEDULA_REPRESENTANTE, NOMBRE_REPRESENTANTE, FECHA_OTORGAMIENTO, CEDULA_CURADOR, NOMBRE_CURADOR, NOMBRE_JUZGADO, FECHA_SENTENCIA, NUMERO_SENTENCIA,
           SELLO_REGISTRO, NUMERO_SIME_TUTELAJE, OBSERVACIONES_ANULAR_TUTELAJE, CERTIFICADO_MATRIMONIO, OFICINA_MATRIMONIO, FECHA_ACTA_MATRIMONIO, TOMO_MATRIMONIO,
           FOLIO_MATRIMONIO, ACTA_MATRIMONIO, CEDULA_CONYUGE, NOMBRE_CONYUGE, FECHA_MATRIMONIO, FECHA_CERTIFICADO_MATRIMONIO, NUMERO_SIME_MATRIMONIO, OBSERVAC_ANULAR_MATRIMON_43115,
           CERTIFICADO_DEFUNCION, OFICINA_DEFUNCION, FECHA_ACTA_DEFUNCION, TOMO_DEFUNCION, FOLIO_DEFUNCION, ACTA_DEFUNCION, FECHA_DEFUNCION, FECHA_CERTIFICADO_DEFUNCION,
           NUMERO_SIME_DEFUNCION, OBSERVACIONES_ANULAR_DEFUNCION, CERTIFICADO_INVALIDEZ, DIAGNOSTICO_INVALIDEZ, FECHA_CERTIFICADO_INVALIDEZ, NUMERO_SIME_INVALIDEZ,
           OBSERVACIONES_ANULAR_INVALIDEZ, BANCO, CUENTA_BANCARIA, NUMERO_SIME_CUENTA, OBSERVACIONES_ANULAR_CUENTA, FICHA, NUMERO_SIME_FICHA, OBSERVACIONES_ANULAR_FICHA,
           MONITOREADO, FECHA_MONITOREO, MONITOREO_SORTEO, OBSERVACIONES_FICHA, SALARIO, PORCENTAJE, NUMERO_SIME_SALARIO, OBSERVACIONES_ANULAR_SALARIO, FECHA_INGRESO,
           FECHA_EGRESO, TIPO, CANTIDAD, MODELO, ANO_REGISTRO, MONTO, NUMERO_SIME_AUTOMOTOR, OBSERVACIONES_ANULAR_AUTOMOTOR, FECHA_NACIMIENTOS, DEPARTAMENTO_NACIMIENTO,
           DISTRITO_NACIMIENTO, NOMBRE_MADRE, CEDULA_MADRE, NOMBRE_PADRE, CEDULA_PADRE, FOLIO_NACIMIENTO, ACTA_NACIMIENTO, TOMO_NACIMIENTO, NUMERO_SIME_NACIMIENTO,
           OBSERVAC_ANULAR_NACIMIEN_13191, TIPO_PROVEEDOR, RUC_ENTIDAD, DENOMINACION_ENTIDAD, NUMERO_SIME_PROVEEDOR, OBSERVACIONES_ANULAR_PROVEEDOR, FECHA_INGRESO_CATASTRO,
           FECHA_EGRESO_CATASTRO, TIPO_CATASTRO, CANTIDAD_INMUEBLE, MONTO_CATASTRO, NUMERO_SIME_CATASTRO, OBSERVACIONES_ANULAR_CATASTRO, FECHA_INGRESO_COTIZANTE, FECHA_EGRESO_COTIZANTE,
           MONTO_COTIZANTE, NOMBRES_EMPRESA, RUC, NUMERO_SIME_COTIZANTE, OBSERVACIONES_ANULAR_COTIZANTE, FECHA_INGRESO_SENACSA, FECHA_EGRESO_SENACSA, TIPO_SENACSA, CANTIDAD_SENACSA,
           MONTO_SENACSA, NUMERO_SIME_SENACSA, OBSERVACIONES_ANULAR_SENACSA, EDICION_RESTRINGIDA, b.NOMBRE NOM_DEPARTAMENTO, c.NOMBRE NOM_DISTRITO  
    From persona a, departamento b,distrito c
    Where a.departamento = b.id and a.distrito = c.id  
      And a.id not in (select id from tmp_persona);

  insert into tmp_clase_pension (ID, VERSION, CODIGO, NOMBRE, GRUPO, FECHA_DECRETO, DECRETO_LEY, REQUIERE_CAUSANTE, REQUIERE_CENSO, REQUIERE_SALDO,
                                AUXILIO, PAGO_UNICO, PARENTESCO_CAUSANTE, CLASE_PENSION_CAUSANTE)
    Select ID, VERSION, CODIGO, NOMBRE, GRUPO, FECHA_DECRETO, DECRETO_LEY, REQUIERE_CAUSANTE, REQUIERE_CENSO, REQUIERE_SALDO,
            AUXILIO, PAGO_UNICO, PARENTESCO_CAUSANTE, CLASE_PENSION_CAUSANTE 
    From clase_pension
    Where id not in (select id from tmp_clase_pension);

  insert into tmp_transicion_pension
    Select * from transicion_pension
    WHERE transicion_pension.id not in( select id from tmp_transicion_pension );

  delete from  fact_pension;

  insert into fact_pension
    Select busca_clave_id,  b.id Id_tiempo, c.id id_pension, d.id id_clasepension, 0 id_estado_pension, i.id_usuario, e.id id_persona,
          case a.estado_final when 1  then 1 else 0 end Solicitada,
          case a.estado_final when 3  then 1 else 0 end Acreditada,
          case a.estado_final when 6  then 1 else 0 end Otorgable,
          case a.estado_final when 7  then 1 else 0 end Otorgada,
          case a.estado_final when 4  then 1 else 0 end Denegable,
          case a.estado_final when 5  then 1 else 0 end Denegada, 
          case a.estado_final when 8  then 1 else 0 end Revocable,  
          case a.estado_final when 9  then 1 else 0 end Revocada, 
          case a.estado_final when 10 then 1 else 0 end Finalizada,
          case a.estado_final when 2  then 1 else 0 end Anulada 
    From tmp_transicion_pension a inner join dim_tiempo b on TO_CHAR(a.fecha,'YYYY') = b.anho_4 And TO_CHAR(a.fecha,'MM') = b.mes  And TO_CHAR(a.fecha,'DD') = b.dia
      inner join tmp_pension c on a.pension = c.id
      inner join tmp_clase_pension d on c.clase = d.id 
      inner join tmp_persona e on c.persona = e.id 
      left outer join dim_usuario i on a.usuario = i.id_usuario;
  return 0;
exception
when others then
  v$msg := SQLERRM;
  raise_application_error(v$err, 'Error al intentar poblar las tablas temporales para generar estadísticas, mensaje:' || v$msg , true);
end;
/
